# Generated by Django 3.0.3 on 2020-02-10 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='efile',
            field=models.FileField(default=datetime.date, upload_to=''),
            preserve_default=False,
        ),
    ]
