# Generated by Django 3.0.3 on 2020-02-10 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mysite', '0002_user_efile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='efile',
        ),
    ]
