# Generated by Django 3.0.3 on 2020-02-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mysite', '0003_remove_user_efile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='efiles',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
