# Generated by Django 3.0.3 on 2020-02-12 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mysite', '0007_auto_20200212_1103'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
