# Generated by Django 3.0.3 on 2020-02-12 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mysite', '0008_auto_20200212_1201'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='regis',
            table='register',
        ),
    ]
