# Generated by Django 3.0.3 on 2020-02-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mysite', '0010_auto_20200212_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='regis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
