# Generated by Django 3.0.3 on 2020-02-13 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mysite', '0011_auto_20200212_1218'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='regis',
            table='registers',
        ),
    ]
